spring:
  datasource:
    type:  com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/george?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: f10011116
  devtools:
    restart:
      enabled: true
server:
  port: 80

